In [1]:
import pandas as pd
import pickle

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import r2_score

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

In [2]:
df = pd.read_csv("insurance.csv")

print(df.head())

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
print(df.shape)

df.info()

(1338, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [4]:
print(df.isnull().sum())

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [6]:
print(df["sex"].unique())

print(df["smoker"].unique())

print(df["region"].unique())

['female' 'male']
['yes' 'no']
['southwest' 'southeast' 'northwest' 'northeast']

In [7]:
X = df.drop("charges", axis=1)

y = df["charges"]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=0
)

In [10]:
X_train.sample(3)

     age     sex    bmi  children smoker     region
183   44  female  26.41         0     no  northwest
718   51  female  36.67         2     no  northwest
403   49    male  32.30         3     no  northwest

In [11]:
X_test.sample(3)

      age     sex     bmi  children smoker     region
364    21  female  21.890         2     no  southeast
1098   52  female  30.875         0     no  northeast
27     55  female  32.775         2     no  northwest

In [12]:
y_train.sample(3)

1059     4462.7218
86      43578.9394
1011    18767.7377
Name: charges, dtype: float64

In [13]:
y_test.sample(3)

434      4243.59005
1256    11436.73815
667     40003.33225
Name: charges, dtype: float64

In [15]:
categorical_features = [
    "sex",
    "smoker",
    "region"
]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ],
    remainder="passthrough"
)

In [20]:
#Linear Regression

lr_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

lr_pipeline.fit(X_train, y_train)

lr_pred = lr_pipeline.predict(X_test)

print(
    "Linear Regression R2 Score:",
    r2_score(y_test, lr_pred)
)

Linear Regression R2 Score: 0.7999876970680433

Accuracy From Linear Regression : 79.99%

In [21]:
#Decision Tree

dt_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", DecisionTreeRegressor(
        random_state=0
    ))
])

dt_pipeline.fit(X_train, y_train)

dt_pred = dt_pipeline.predict(X_test)

print(
    "Decision Tree R2 Score:",
    r2_score(y_test, dt_pred)
)

Decision Tree R2 Score: 0.7142644756791616

Accuracy From Decision Tree : 71.42%

In [22]:
#Random Forest

rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=100,
        random_state=0
    ))
])

rf_pipeline.fit(X_train, y_train)

rf_pred = rf_pipeline.predict(X_test)

print(
    "Random Forest R2 Score:",
    r2_score(y_test, rf_pred)
)

Random Forest R2 Score: 0.8774128912084722

Accuracy From Random Forest : 87.74%

In [23]:
#SVM

svm_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", SVR())
])

svm_pipeline.fit(X_train, y_train)

svm_pred = svm_pipeline.predict(X_test)

print(
    "SVM R2 Score:",
    r2_score(y_test, svm_pred)
)

SVM R2 Score: -0.10392794578718845

Accuracy From SVM : 10.39%

In [24]:
#Random Forest Pipeline is taken since it gives the most accuracy of all.
pickle.dump(
    rf_pipeline,
    open(
        "insurance_model.pkl",
        "wb"
    )
)

print("Model Saved")

Model Saved